### PR TITLE
Add gauges to dashboard

### PR DESCRIPTION
**Pull request by donoftime**
Here is a pass at putting some gauges on the dashboard. What do you think?

dashboard

I also took a couple of screenshots of the pie on its boundaries,negative remaining health and zero damage:

YOU DIED and all clear

Looking at that last screenshot I can see I still need to work on the 0 damage case to make it more clear. Right now it looks like you'll take 36.7 damage, but you'll still be okay or something. The tooltip explains that it is the remaining health, but I don't want to rely on that.

It's 2:30am though, so I'm going to put that off until next time. Note that I based this branch off of the c3+d3 dependencies commit, so it can be treated independently of the habit history chart.

### CODE REVIEW

**Comment by Alys** [comment]
I think that has a lot of potential!

We can get rid of the background colours that are on the current dashboard - they're only to show good versus neutral versus bad, and the colours on the gauges will do that. However we'll have to ensure that the gauge colours are distinguishable by people with all (or at least almost all) forms of colour blindness. I use https://chrome.google.com/webstore/detail/spectrum/ofclemegkcmilinpcimpjkfhjfgmhieb for that.

You're wise to not rely on tooltips - we've noticed in HabitRPG that people often don't realise they can hover to see them. If at all possible, I'd like the gauges to be understandable at a glance, including by people who aren't very technically proficient. Where there's two numbers on a pie chart, it's probably necessary to have an always-visible description next to each number. If that's not possible in a way that looks nice, then maybe show just the most important number and let the size of the other pie slice hint at the other number. I think that would be appropriate for the health-remaining portion of the "damage to you" pie.

Thank you for this! I predict that the change will be very popular! Habiticans love pretty colours and attractive tools!

**Comment by donoftime** [comment]
I followed your suggestions and removed the backgrounds from the charts, and also removed the extra pie label (for 'Remaining Health'). 

I tried putting the labels on the pie itself, but even using small labels like "HP" and "DMG" I couldn't get it to look right. But what I have now just has the chart title + 1 number, which I think is infinitely more clear than what I had before. The tooltips are still there of course for bonus information.

Here is a screenshot:
no_background_or_extra_value

I tried installing the extension you mentioned, but I was unable to have it change the colors on any site :confounded:. I am color deficient myself, and normally use colorblind mode whenever it's available, so I certainly understand your concern. I can distinguish the colors I currently have - but that just scratches one deficiency off the list. I'll keep trying to get the extension to work (or to find an alternative), but please let me know of any colors you see that you want me to change!

**Comment by Alys** [comment]
I'm happy to do all the colour-blindness testing if you like!

This is looking really good!

**Comment by donoftime** [comment]
I won't turn down free testing, lol.

I'm glad you like it, now I just hope I can make it past code review :sweat_smile:

**Comment by Alys** [comment]
I've merged this locally to test it and I love it! I definitely want it and it will be worth another contributor tier. Please continue! 

The code's fine too, and the colours pass all the colour blindness tests. The red and green seem rather aggressively bright to me, but that might just be because I'm used to the more muted colours. I'll see what it all looks like when it's finished.

The gauges take up more space than the tiles of course, so we might need to shrink them, or do something different for some of the other tiles. We can convert the tiles for "To-Dos Due Today" and "Damage to Boss"/"Quest Progress" to some other format (maybe a single line of text above the gauges, if nothing better occurs to us). "Damage to Party" also probably doesn't need to be a gauge since it's a single number.

Have you noticed the "Drop Count" tile? It only appears if you choose to look at "Drops Received Today" section because some users might not want to know when they've reached their drop cap (less motivation). Other users love seeing their counts, so we definitely want a pretty gauge for that.

I think the text labels under each gauge should have a larger font. They're almost at the point where I have to look carefully to read them and some of our users are likely to have worse eyesight than mine.

Could you please add a brief comment to the code to state the website where the libraries come from? I've found the site, but it will be helpful to have it recorded for future reference.

Thank you for doing this! It's going to be a great improvement!

**Comment by donoftime** [comment]
I added the gauge for the Drop Count, and added animations to them. Here's a quick recording:

cinnamon-20150401-1

I forgot to catch it in the recording, but the drop count gauge remains shown/hidden on the refetch of the data as well. 

You'll notice that I also moved the value-only items to their own part of the list, so now the list looks like

* `#DASHBOARD`
    * `.visualized`
    * `.valueOnly`

This way they're logically, as well as visually, separated. I also removed the restriction on their size so that they expand to be the same size as the charts.

**Comment by donoftime** [comment]
I think that addressed all the comments so far on this PR (I also increased the fontsize for the gauges). Let me know what else you see this weekend!

**Comment by Alys** [comment]
This seems odd:
screen shot 2015-04-05 at 3 40 50 pm
Is it the grey portion that shows the number of incomplete Dailies? That looks about right for the proportions, but I would expect the red colour to indicate the proportion of incomplete Dailies. Is it possible to swap them around, and maybe change the grey colour to green?

**Comment by donoftime** [comment]
I rebased onto master and changed the gauge color for the dailies incomplete to be green. So now the gauge will fill up as dailies are completed (being green the entire time), while still reporting the incomplete number as the label. 

green_gauge

That way the gauge is the carrot showing progress, and the label is the stick showing what you have left.

**Comment by donoftime** [comment]
What do you think about the gauge change? Any other enhancements you would like to see on the dashboard? 

I am also looking around for what to do next, like maybe another trend chart for dailies, or perhaps a word cloud for todos. I'll be busy this next week, but after that I have so many personal projects (like this one) that I want to do that I want to have them all lined up and ready to work on :smile:

**Comment by Alys** [comment]
I'm really sorry; I've been so busy with habitrpg.com changes. :( I'll try
to reply in a couple of days, but if not, definitely this weekend.

**Comment by donoftime** [comment]
Let me know if I need to tweak, twist, turn, tip, transform, or trash anything :smile:

**Comment by Alys** [comment]
Arrgh, sorry, I should have replied weeks ago. :(

I want to make the remaining dashboard tiles look more consistent with the new gauges - perhaps rectangles of similar colours or something, maybe as a row under the gauges so that similar pieces of information can be near each other (e.g., Damage to Party underneath Damage to You). Would you like to experiment with that? It's okay if you don't - I'll try to fit it in soon.

The remaining dashboard tiles are, from memory:
- Resting in the Inn
- Damage to Party
- To-Dos Due Today
- Damage to Boss / Quest Progress

I have a feeling that some people will find the Dailies Incomplete gauge to be confusing, since the increasing coloured part shows the opposite of what the gauge label says. I'm not sure what to do about it though, if anything.

**Comment by donoftime** [comment]
I still plan to implement your suggestions, I have just been very busy. I will see what I can do in the next week or two. Sorry for the delay!

**Comment by Alys** [comment]
Please don't apologise to me! I had kept you waiting far longer. I'm just grateful for whatever time you can spare for this!

**Comment by donoftime** [comment]
All those commits above are just a rebase of this branch onto your recent changes from master. I'm going to reorient myself in the new code and see if my fresh brain has any better ideas on visualization than last time I looked at this.

**Comment by donoftime** [comment]
^ That commit updates the doc with what I did to get up to speed. Please scrutinize the changes [there](https://github.com/donoftime/tools-for-habitrpg/commit/752f979e55185b8b70b56cec85302b550662b2c2) in case I'm operating on old information :smile:

**Comment by donoftime** [comment]
One more thing I've come across - do you have some party testdata I could have? I want to add it to the `testdata/` directory so that I can dev / test without a webserver running - much like I did with the test data [you gave me for the other ajax calls](https://github.com/Alys/tools-for-habitrpg/pull/19#issuecomment-84531693). In the meantime I think I can get by with just declaring the `partyJsonString` by hand as `{}`.

**Comment by donoftime** [comment]
Okay, so I think I'm back up to speed (I'm just using my own limited user data as test data for now). Here is what I have pushed to the branch so far...

image

...so to clarify the requirements before I dive in, we're looking for:

>  ... the remaining dashboard tiles ... as a row under the gauges so that similar pieces of information can be near each other ...

I think that one's done from visual inspection, so that's a :white_check_mark: ? I only have my own data for testing tonight, so I may be off base on what you were looking for on that one.

> ... some people will find the Dailies Incomplete gauge to be confusing, since the increasing coloured part shows the opposite of what the gauge label says ...

I'm interpreting that as meaning I should go through the code and make all the references to "incomplete dailies" into the positive opposite, so it's all "complete dailies". That way the number and gauge are in alignment. If were wanting to use the stick instead of the carrot, I could instead flip the gauge to be negative (where empty is good) - whichever you had in mind!
 
---

I think that covers what is left - but please elaborate if I overlooked over something important! 

There's also always the option to not add gauges, as they might just distract from the rest of the page where the *real* data is ... so no hard feelings if you just wanted to close this PR :smile:

**Comment by MathWhiz** [comment]
@Alys @donoftime Just a suggestion, but if the "Dailies Incomplete" fills up with green as you complete dailies, would it be better labeling it "Dailies Complete"?

**Comment by donoftime** [comment]
@MathWhiz I am all for that - not only from the benefit of making the gauge make more sense, but also because it follows the rule to "stay positive" with variables (which will simplify the code as well). So from a technical standpoint, I am in total agreement with you.

However, the more important consideration is the psychological component for the user. Was @Alys going for a 'stick' with an *dailies incomplete* metric, or is it alright to change to a 'carrot' with a *dailies complete* metric? 

I left it as incomplete, since that is the way it was originally - but the graphic/numeric mismatch there clearly sent our heads spinning :confounded: 

It really comes down to preference and what we think will be most intuitive to users - and I defer to @Alys's judgement on that. Just let me know what we want and I can bring this up to date. Of course that depends on if we still want the gauges, since "don't use them" is a perfectly legitimate choice as well :smile:

**Pull request closed without merging**
