### PR TITLE
Introduce charts for visualization

### PR DESCRIPTION
**Pull request by donoftime**
Hello!

I was [playing around with the API for HabitRPG](https://github.com/donoftime/habitata) when I noticed that there weren't any charts on oldgods.net! Since you already have all the data nicely partitioned and displayed, I figured I could just slip in and add some visualizations. 

I have a lot more ideas, like changing the dashboard values at the top to be [gauges](http://c3js.org/samples/chart_gauge.html), but I wanted to see what you thought about this chart first. I figure I should get approval of a simple chart on a random side page before I tried anything too crazy. There are also 9001+ charting libraries based on D3 out there...

Here is a screen shot of what the chart looks like, but to get the full look and feel you should pull the code and take a look. The best part about it is how it changes dynamically as you interact (document driven design ftw).

visualization

You may notice that the legend entries are being escaped which ruins any emoji or images. It is being done somewhere deep in the library, but I haven't decided if I should try to stop/undo it, leave it be, or remove those elements. The only thing that worries me is when someone uses a really large image in the habit/daily/todo description which would throw off the legend...but, I figured why hold off. Let's see if anyone even wants these charts before I spend more time on them :sweat_smile:

### CODE REVIEW

**Comment by Alys** [comment]
I think I am in love with that screen shot...

Give me a few hours to get some other things done :(  and then I'll pull down the code and examine it, and then probably squeal excitedly for a few minutes, and then get back to you. :)

**Comment by Alys** [comment]
I like your idea about the gauges too and I'd be happy to consider it if you did another PR. There's a caveat that I'd want the numbers to still be clearly visible (e.g., any graphical effects or background colours shouldn't obscure them, especially for people with colour-blindness or other visual impairments) but from the sample on the page you linked to, it looks like that won't be a problem. I'm kind of excited about gauges - it could really pretty-up the page.

**Comment by Alys** [comment]
I love this idea in theory, but in practice, for a subscriber with a lot of history, it gets a bit cramped... :)
http://i.gyazo.com/65f01e984ca2d021571965d0c26ac6c6.png
http://i.gyazo.com/547e105497761147802ec9fed0a5c117.png

I'm not too concerned about the emoji displaying as image tags, at least initially, because I'm not sure how many people use them as extensively as I do (although we will have to ensure that they don't overrun the axis). 

I think we will need to take into account people with large histories before this can be released. One possibility would be to show just the past x weeks of data - certainly better than nothing! But if you have any better ideas, I'm happy to go with whatever you think.

In case you want data for testing, I've uploaded my Habits API objects for both of those accounts to these files:
http://oldgods.net/habitrpg/habits-very-many.json
http://oldgods.net/habitrpg/habits-many.json
There's nothing private in there so use them as you wish. I don't know if you've noticed, but the DDT has quick-and-dirty support for reading data from a local webserver, so you could hack together a test using my Habits objects with that. See the "TST" section at about line 87. The important part of the '/cgi-bin/hrpg_user.pl' script is these two lines:
````
print header('application/json');
print `cat $file`;
````
where $file contains the path to a file that contains the full user object. Tell me if that's too obscure to be understandable.


Also, if you'd like to submit other features or improvements (either before this fix, or after, or instead of), I would be very interested to see what you can come up with!

**Comment by donoftime** [comment]
Haha, I was wondering what it would do at scale :sweat_smile: 

I 100% agree that we need to make it look good for people with long histories, since they are the ones who need it most to find trends! 

Thank you for the test data, I'll see what I can do. I'm hoping to fix the scaling and legend problem so people can see the entire timeline at once (and zoom using the subchart range), but if that is not possible then I will try to either have PREV/NEXT controls to unload+load chunks of the data for viewing, or maybe even a datepicker. 

I only have about 45 mins to play with it now before I need to head out, so I'll see what I can get and continue this evening.

**Comment by donoftime** [comment]
Using the test data, I did a bit of reformatting and optimizations. I ended up going with your suggestion to just limit the data for now. I put as much in the chart as it can take before performance degradation starts. I also switched to a zoom instead of a subchart. Here are the screenshots using the test data:

## habits-many

habits-many

## habits-very-many

habits-very-many

**Comment by donoftime** [comment]
Here is a screenshot of what I just pushed up (using the habits-very-many.json).

time_scale_and_interpolation
 
## Removal of the unnecessary Recent Habits button

It didn't really add any value, and would result in some unsuspected behavior if you scrolled after clicking then toggled a habit (the zoom would reset). 

## Using a timeseries instead of categories

This gives a more accurate time scale on the x-axis, and also lightens up the data load a bit since the data is coming in as columns now.

## Interpolating values between data points

Before I had just used `0` whenever I didn't have a value for a habit on a day. That resulted in the sporadic graphs you see above which really only told you which days a change was made. My new technique is almost as simple, in that it uses the previous value for that habit if one doesn't exist. That way you still see the changes when a new value comes in, but now you get to see any trend that is forming over time. For example:

```
Before: [ 0, 0, 1, 2, 3, 0, 0, 0, 4, 0, 2, 0, 0, 0, 1, 0 ]
After:  [ 0, 0, 1, 2, 3, 3, 3, 3, 4, 4, 2, 2, 2, 2, 1, 0 ]
```

It smooths out the graph to estimate what the values actually are in the absence of data. 

---

What do you think? Headed in the right direction?

**Comment by Alys** [comment]
I'm sorry I haven't got back to you yet. I love the look of those charts! I'll examine this thoroughly in the next two days, and your other to PRs as well.

**Comment by donoftime** [comment]
No worries! 
I just pushed a little cleanup commit that moved some functions to a more appropriate scope, so hopefully that simplifies it a bit :see_no_evil:

**Comment by Alys** [comment]
Lovely! Thank you!

**Comment by Alys** [comment]
I am definitely going to accept this and you'll get a contributor tier for it. The code's good and I can see nothing that I want to change in it except:

I'd like it to be in its own section instead of included with the list of Habit data. Part of the reason for that is that if you're scrolling down the page to get to the list data using a trackpad or scroll wheel, then your scrolling is intercepted by the chart unless your cursor happens to be on the far side of the page, and that's going to be frustrating if you do want to scroll past it. Moving the chart to its own section avoids that problem. Also I think it's definitely good enough to have its own section, and a new section title means that more people are likely to notice it.

Would you like to put it into a new section or would you like me to? I'm fine with either option. I'm not sure how clear my code is for creating new sections, so you might want me to do it. :)

Do you have any preference for the section title? Habit Chart? Habit Visualisation? Habit ...? It should start with Habit for consistency with the other sections.

The chart section should be above the history section because I think it will be more popular.

I would also like an explanation to be above the chart, saying what it shows and how to use it. I know it's fairly obvious after a minute or two of playing around with it, but we do have users that will feel intimidated by controls that they don't understand, so some words would help. Just something fairly brief about how you can turn off individual Habits by clicking on them; hover over a point to see the value at that date; scroll up and down within the chart to zoom in or out. Would you care to write that? If you don't want to, are there any controls that I've missed?

**Comment by donoftime** [comment]
I had wondered if the data-tool counted for contributor tiers - that's cool that it does!

I have your comments and suggestions for all the pull requests broken down on my HabitRPG todo list. But now that you're saying this is even more tied to HabitRPG than I thought, does that mean I should have been tracking this on a Trello board or something? Otherwise I'll just keep the tasks in my HabitRPG and reap that sweet, sweet EXP...

I'll try to address all your comments this week if I can, but one that I can answer quickly: What do you think about the title being **Habit Trends** ? Since the chart focuses on the development of a habit over time, I think the trend is the best information users can get out of this particular chart.

**Comment by Alys** [comment]
If you use Trello for my tool, you are dead to me. ;)  What you've been doing is all that's needed.

"Habit Trends" is perfect!

**Comment by donoftime** [comment]
I rebased onto master (hence all the commits). I implemented your suggestions - here's a screenshot:

habit_trends

I want to fix the markdown ones, because they're making the tooltips enormous. I'll see what I can do about that tomorrow.

**Comment by Alys** [comment]
That's fantastic! Good wording, and the Toggle All button will be very useful!

If you happen to get markdown working across the whole tool, that will probably count (partially?) towards another tier, in addition to the one you'll get for the Habit Trends feature, although I might have to confirm that with the staff.

With the way tiers work, the first two or three are fairly easy to get, but more work is required for each tier after that. Often a few small or medium contributions combine to give a single high tier. The higher tiers usually require approval by the staff. But we aren't stingy about this sort of thing and the work you're doing is excellent, so you can be sure you'll be rewarded for it. I'll sort out exactly how much once things are ready to be merged. 

The test framework and documentation in one of your other pull requests will probably count too.

**Comment by donoftime** [comment]
Whatever y'all think is appropriate is fine by me - I really just wanted some charts :smile: 

There's one more thing I want to do with this chart as well. I noticed the habits in HabitRPG decay over time, and I want that built in to the chart. What I have now just uses the previous value when data is missing for a day, but it would be more appropriate to use the previous value * some decaying factor. Unless you know that factor off hand, I'll comb through the HabitRPG source and see if I can find it. That way neglected habits will properly decay rather than maintaining their value.

**Comment by Alys** [comment]
Interesting idea! The code you want is in common/script/index.coffee around line 1522
````
      user.habits.forEach (task) -> # slowly reset 'onlies' value to 0
        if task.up is false or task.down is false
          if Math.abs(task.value) < 0.1
            task.value = 0
          else
            task.value = task.value / 2
````

**Comment by donoftime** [comment]
Screenshot with habit decay and rendered markdown:

decay_and_markdown

Note that I had to fix the markdown in the example data which had an incorrect syntax, so you might want to update yours as well. Proper syntax for an image and text is:

```
![tootip](http://url/to/image.png) Words next to the image
```

**Comment by Alys** [comment]
Looks good!

So the library you're using doesn't work if the title attribute is specified? Is it too late to choose another library? The attribute is part of the [markdown spec](http://habitrpg.wikia.com/wiki/Markdown_Cheat_Sheet) that HabitRPG uses ([see also here](http://daringfireball.net/projects/markdown/syntax#img)) so there'll probably be a lot of users using it.

**Comment by donoftime** [comment]
I was not aware you could specify the title attribute that way in markdown. That's what I get for not checking the spec when I saw an alternate syntax...

I will revert the test data to include the title attr and ensure it works. Using example data on the console, it would appear the library *does* support it - so I will determine what was wrong in this case.

```
> marked("![wat](http://i.imgur.com/synonSr.png \"wat\")");
    "<p><img src="http://i.imgur.com/synonSr.png" alt="wat" title="wat"></p>
    "
```

**Comment by donoftime** [comment]
The problem was with the input string being escaped before they got to the `marked()` call. To resolve that, I just render all markdown immediately before rendering emoji, and I replaced the entity escaping that you had in place by enabling the sanitization built into the markdown library. That way critical entities (like the quote) will not be escaped before parsing the markdown - but afterwards will still be properly escaped:

```
 -> marked("&<>\"'", {sanitize: true})
 <- "<p>&amp;&lt;&gt;&quot;&#39;</p>
      "
```

**Comment by donoftime** [comment]
I went ahead and rendered the markdown for task notes as well:

markdown_in_notes

I clicked through all the pages and didn't come across any other fields that need sanitizing+rendering, so I think the markdown translation is done?

**Comment by donoftime** [comment]
I said I was done because I knew as soon as I said it I would think of something else. In this case, it was the user's profile name in the top right which was unsanitized and unrendered. Not that I would reasonably think someone would put markdown in their username, but it would also be pretty awesome to have yourself show up in the tavern as  success - so I bet someone will try.

But really it's just a reflected XSS attack vector that I figured I should close while I'm at it.

With that I think I have addressed all of your comments (and also made the tooltips smaller by rendering markdown). Let me know what you see in **CODE REVIEW ROUND TWO** :smile:

**Comment by Alys** [comment]
Ha! Awesome! I probably won't get a chance to look at this properly until the weekend, but it's a four day weekend so YAY definitely then.

FYI out of interest, one Habitican uses :hibiscus: for their name (: hibiscus :).

Is there a particular site that has images like those trolls and goblins?

**Comment by donoftime** [comment]
> FYI out of interest, one Habitican uses :hibiscus: for their name (: hibiscus :).

Hahaha, I love people - always doing the unexpected :smile: 

I just pushed up another commit that will render emoji in the profile name as well, so :hibiscus: will see their name 'spelled' properly. 

> Is there a particular site that has images like those trolls and goblins?

Possibly? 

I unfortunately don't know, since those To-dos actually came from my favorite challenge (so far) [Restore Faerie Falls (Deep Clean the Shower)](https://habitrpg.com/#/options/groups/challenges/754ff88f-4253-47bb-9732-07820384e5f9).

**Comment by Alys** [comment]
"render emoji in the profile name" -- Thank you!

What a cute challenge! It looks like the images were all created by our own pixel artists. I'll have to see if we can get permission to add them to the wiki for reuse.

**Comment by Alys** [comment]
When I have your UUID, you'll get Tier 2 for adding markdown support to the entire tool and Tier 3 for these charts.

**Comment by Alys** [comment]
Tiers awarded. 

I've reverted the table of contents to the four-column format because six columns were wrapping on my laptop's smaller screen: http://i.gyazo.com/93ab2347e718e3984203d249bc5feb9b.png
I'm open to more changes to the ToC, as long as it doesn't take up too much vertical space. :)

The Habits Trend section is live now and I've posted about it in the Tavern.

**Pull request merged**
